apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: blog-route
spec:
  hostnames:
    - blog.blunders.dev
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-external
      namespace: envoy-gateway
      sectionName: https
  rules:
    - backendRefs:
      - kind: Service
        name: blunders-blog-service
        port: 80
